### ISSUE TITLE
Error with stats.MedianSurvivalTime while running with 'NoPlot'=1

### ISSUE THREAD

**Issue by ashrafinia** [aebergl/MatSurv#3]
Thanks for the great job. Using the command with `'NoPlot'=1` option prompts the following error:

```
Reference to non-existent field 'MedianSurvivalTime'.
Error in MatSurv (line 478)
        fprintf('Median Survival Time: (%s) =
        %g\n',stats.GroupNames{i},stats.MedianSurvivalTime(i)) 
```

This is because `stats.MedianSurvivalTime` is defined within the big "if" condition handling the plot, so when `~options.NoPlot=0`, it does not calculate that and returns an error. 

I can go ahead and comment lines 477 to 479 that later call `stats.MedianSurvivalTime`, but then the actual median value is not saved under `stats` and is not easily retrievable.

**Comment by aebergl** [comment]
Thanks!
I have now fixed the bug that you found and median survival time is calculated even if no plot is created.  
If you find other unexpected features or you have some ideas how to make MatSurv better please let me know!

All the best,

/Anders
