### ISSUE TITLE
An issue when one of the groups has only one element

### ISSUE THREAD

**Issue by ashrafinia** [aebergl/MatSurv#4]
Just found another issue, when one of the groups has just one element, the following error is given:

`
In an assignment  A(:) = B, the number of elements in A and B must be the same.
Error in MatSurv>MatSurvCalculateTables (line 686)
nf(2:end) = nf(2:end) - mf_cumsum(1:end-1);
Error in MatSurv>MatSurvCreateTable (line 669)
    [KM_Events, KM_ALL, Censored_Points] =
    MatSurvCalculateTables(tf,DATA.GROUPS(i).TimeVar,DATA.GROUPS(i).EventVar,[]);
    Error in MatSurv (line 252)
[DATA] = MatSurvCreateTable(DATA); `

I think I found a fix for it. Change the line 681 from 
`mf = sum(repmat(TimeVar,1,length(tf)) == repmat(tf',length(TimeVar),1))';` 
to 
`mf = sum(repmat(TimeVar,1,length(tf)) == repmat(tf',length(TimeVar),1),1)';`

It is basically the same thing, but if the sum order is not specified, when having a one-element tf, `cumsum()` returns a 1x1 element instead of a 1x2.

**Comment by aebergl** [comment]
Hi again,
Thanks for identifying and fixing this bug! 
I have updated my code accordingly.
Let me know if there is any other things you would like to include or improvements that could be done.

/Anders
