### ISSUE TITLE
Plotting groups with no events

### ISSUE THREAD

**Issue by iahncajigas** [aebergl/MatSurv#6]
I have a dataset in which one of the groups does not have any events and the current implementation does not plot the appropriate horizontal line at 1. I modified the function with the following code at line 363 to appropriately deal with this case:
if(~isinf(DATA.GROUPS(i).KM_ALL(2,1)))
      S(i)=stairs(axh_KM,DATA.GROUPS(i).KM_ALL(:,1),DATA.GROUPS(i).KM_ALL(:,2),...
                      'Color',cMAP(i,:),'Linewidth',options.LineWidth,'LineStyle',LineStyles{i});
else
      axes(axh_KM)
      v=axis; % v has the appropriate x and y axis limits. Could also loop over the available data to ensure 
                  % that these limits are accurate.
      S(i)=stairs(axh_KM,[0 v(2)],DATA.GROUPS(i).KM_ALL(:,2),...
                      'Color',cMAP(i,:),'Linewidth',options.LineWidth,'LineStyle',LineStyles{i});
end

**Comment by aebergl** [comment]
Hello,
Thanks for using MatSurv and reporting your problem. I'm a bit confused with your error, I have tested groups with no events and it usually works. For examples the following commands generates a perfect KM-plot with a horizontal line at Y=1
load('Freireich_Example_1.mat');
EventVar(1:9)=0; %Remove all events for Group 1
MatSurv(TimeVar, EventVar, GroupVar);

Would you be able to share the data so I can reproduce your results?

All the best,

/Anders
